ALTER TABLE jxc_bom
  ADD COLUMN IF NOT EXISTS style_code VARCHAR(50),
  ADD COLUMN IF NOT EXISTS style_name VARCHAR(100),
  CHANGE COLUMN version version_no VARCHAR(20) DEFAULT '1.0',
  ADD COLUMN IF NOT EXISTS effective_date DATE,
  ADD COLUMN IF NOT EXISTS remark VARCHAR(255);
