CREATE TABLE IF NOT EXISTS jxc_sys_user (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  dept_id BIGINT NULL,
  username VARCHAR(64) NOT NULL,
  real_name VARCHAR(64) NULL,
  password VARCHAR(255) NULL,
  store_id BIGINT NULL,
  store_name VARCHAR(128) NULL,
  remark VARCHAR(255) NULL,
  permissions TEXT NULL,
  data_auth TEXT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id),
  UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS jxc_sys_role (
  role_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  role_key VARCHAR(64) NOT NULL,
  role_name VARCHAR(64) NOT NULL,
  data_scope CHAR(1) DEFAULT '1',
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (role_id),
  UNIQUE (role_key)
);

CREATE TABLE IF NOT EXISTS jxc_sys_dept (
  dept_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  ancestors VARCHAR(255) NULL,
  dept_name VARCHAR(64) NOT NULL,
  order_num INT NOT NULL DEFAULT 0,
  leader VARCHAR(64) NULL,
  phone VARCHAR(20) NULL,
  email VARCHAR(64) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (dept_id)
);

CREATE TABLE IF NOT EXISTS jxc_sys_post (
  post_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  post_code VARCHAR(64) NOT NULL,
  post_name VARCHAR(64) NOT NULL,
  post_sort INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (post_id),
  UNIQUE (post_code)
);

CREATE TABLE IF NOT EXISTS jxc_sys_user_post (
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS jxc_sys_role_dept (
  role_id BIGINT NOT NULL,
  dept_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, dept_id)
);

CREATE TABLE IF NOT EXISTS jxc_wf_model (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_key VARCHAR(128) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(128) NULL,
  bpmn_xml CLOB NOT NULL,
  version INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (model_key)
);

CREATE TABLE IF NOT EXISTS jxc_wf_model_publish (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_id BIGINT NOT NULL,
  deployment_id VARCHAR(64) NOT NULL,
  process_def_id VARCHAR(64) NOT NULL,
  process_def_key VARCHAR(128) NOT NULL,
  process_def_version INT NOT NULL,
  published_by BIGINT NULL,
  published_at TIMESTAMP NULL,
  remark VARCHAR(255) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS jxc_wf_biz_process_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  biz_type VARCHAR(64) NOT NULL,
  process_def_key VARCHAR(128) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  start_condition CLOB NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (biz_type)
);

CREATE TABLE IF NOT EXISTS jxc_wf_instance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  proc_inst_id VARCHAR(64) NOT NULL,
  business_key VARCHAR(128) NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_id VARCHAR(64) NOT NULL,
  title VARCHAR(255) NULL,
  initiator_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'running',
  start_time TIMESTAMP NULL,
  end_time TIMESTAMP NULL,
  current_task_names VARCHAR(512) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (proc_inst_id)
);

CREATE TABLE IF NOT EXISTS jxc_wf_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id VARCHAR(64) NOT NULL,
  proc_inst_id VARCHAR(64) NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_id VARCHAR(64) NOT NULL,
  node_key VARCHAR(128) NOT NULL,
  node_name VARCHAR(255) NOT NULL,
  assignee_id BIGINT NULL,
  candidate_summary VARCHAR(512) NULL,
  due_time TIMESTAMP NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'todo',
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (task_id)
);

CREATE TABLE IF NOT EXISTS jxc_wf_task_action_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  proc_inst_id VARCHAR(64) NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  action VARCHAR(32) NOT NULL,
  operator_id BIGINT NOT NULL,
  comment CLOB NULL,
  attachments_json CLOB NULL,
  created_at TIMESTAMP NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS jxc_sales_order (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  doc_no VARCHAR(50) NULL,
  order_type TINYINT NULL,
  doc_date DATE NULL,
  store_id BIGINT NULL,
  customer_id BIGINT NULL,
  operator_id BIGINT NULL,
  status TINYINT NULL,
  settle_status TINYINT NULL,
  total_amount DECIMAL(10,2) NULL,
  discount_amount DECIMAL(10,2) NULL,
  other_fee DECIMAL(10,2) NULL,
  actual_amount DECIMAL(10,2) NULL,
  paid_amount DECIMAL(10,2) NULL,
  remark VARCHAR(500) NULL,
  audit_by BIGINT NULL,
  audit_time TIMESTAMP NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS jxc_product_category (
  category_id BIGINT NOT NULL AUTO_INCREMENT,
  parent_id BIGINT NULL,
  category_name VARCHAR(100) NOT NULL,
  sort INT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS jxc_product_brand (
  brand_id BIGINT NOT NULL AUTO_INCREMENT,
  brand_name VARCHAR(100) NOT NULL,
  sort INT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (brand_id)
);

CREATE TABLE IF NOT EXISTS jxc_product_spu (
  spu_id BIGINT NOT NULL AUTO_INCREMENT,
  spu_name VARCHAR(255) NOT NULL,
  category_id BIGINT NULL,
  unit VARCHAR(20) NULL,
  brand_id BIGINT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (spu_id)
);

CREATE TABLE IF NOT EXISTS jxc_product_sku (
  sku_id BIGINT NOT NULL AUTO_INCREMENT,
  spu_id BIGINT NOT NULL,
  sku_code VARCHAR(100) NOT NULL,
  attr1 VARCHAR(50) NULL,
  attr2 VARCHAR(50) NULL,
  purchase_price DECIMAL(10, 2) NULL,
  retail_price DECIMAL(10, 2) NULL,
  wholesale_price DECIMAL(10, 2) NULL,
  weight DECIMAL(10, 2) NULL,
  warning_qty INT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (sku_id)
);

CREATE TABLE IF NOT EXISTS jxc_inventory (
  inventory_id BIGINT NOT NULL AUTO_INCREMENT,
  warehouse_id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  qty INT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  PRIMARY KEY (inventory_id)
);

CREATE TABLE IF NOT EXISTS oauth2_registered_client (
  id VARCHAR(100) NOT NULL,
  client_id VARCHAR(100) NOT NULL,
  client_id_issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  client_secret VARCHAR(200) DEFAULT NULL,
  client_secret_expires_at TIMESTAMP DEFAULT NULL,
  client_name VARCHAR(200) NOT NULL,
  client_authentication_methods VARCHAR(1000) NOT NULL,
  authorization_grant_types VARCHAR(1000) NOT NULL,
  redirect_uris VARCHAR(1000) DEFAULT NULL,
  post_logout_redirect_uris VARCHAR(1000) DEFAULT NULL,
  scopes VARCHAR(1000) NOT NULL,
  client_settings VARCHAR(2000) NOT NULL,
  token_settings VARCHAR(2000) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oauth2_authorization (
  id VARCHAR(100) NOT NULL,
  registered_client_id VARCHAR(100) NOT NULL,
  principal_name VARCHAR(200) NOT NULL,
  authorization_grant_type VARCHAR(100) NOT NULL,
  authorized_scopes VARCHAR(1000) DEFAULT NULL,
  attributes BLOB DEFAULT NULL,
  state VARCHAR(500) DEFAULT NULL,
  authorization_code_value BLOB DEFAULT NULL,
  authorization_code_issued_at TIMESTAMP DEFAULT NULL,
  authorization_code_expires_at TIMESTAMP DEFAULT NULL,
  authorization_code_metadata BLOB DEFAULT NULL,
  access_token_value BLOB DEFAULT NULL,
  access_token_issued_at TIMESTAMP DEFAULT NULL,
  access_token_expires_at TIMESTAMP DEFAULT NULL,
  access_token_metadata BLOB DEFAULT NULL,
  access_token_type VARCHAR(100) DEFAULT NULL,
  access_token_scopes VARCHAR(1000) DEFAULT NULL,
  oidc_id_token_value BLOB DEFAULT NULL,
  oidc_id_token_issued_at TIMESTAMP DEFAULT NULL,
  oidc_id_token_expires_at TIMESTAMP DEFAULT NULL,
  oidc_id_token_metadata BLOB DEFAULT NULL,
  refresh_token_value BLOB DEFAULT NULL,
  refresh_token_issued_at TIMESTAMP DEFAULT NULL,
  refresh_token_expires_at TIMESTAMP DEFAULT NULL,
  refresh_token_metadata BLOB DEFAULT NULL,
  user_code_value BLOB DEFAULT NULL,
  user_code_issued_at TIMESTAMP DEFAULT NULL,
  user_code_expires_at TIMESTAMP DEFAULT NULL,
  user_code_metadata BLOB DEFAULT NULL,
  device_code_value BLOB DEFAULT NULL,
  device_code_issued_at TIMESTAMP DEFAULT NULL,
  device_code_expires_at TIMESTAMP DEFAULT NULL,
  device_code_metadata BLOB DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oauth2_authorization_consent (
  registered_client_id VARCHAR(100) NOT NULL,
  principal_name VARCHAR(200) NOT NULL,
  authorities VARCHAR(1000) NOT NULL,
  PRIMARY KEY (registered_client_id, principal_name)
);

CREATE TABLE IF NOT EXISTS jxc_sales_order (
  order_id BIGINT NOT NULL AUTO_INCREMENT,
  doc_no VARCHAR(50) NOT NULL,
  order_type TINYINT NOT NULL,
  doc_date DATE NULL,
  store_id BIGINT NULL,
  customer_id BIGINT NULL,
  operator_id BIGINT NULL,
  status INT NULL,
  settle_status INT NULL,
  total_amount DECIMAL(10, 2) NULL,
  discount_amount DECIMAL(10, 2) NULL,
  other_fee DECIMAL(10, 2) NULL,
  actual_amount DECIMAL(10, 2) NULL,
  paid_amount DECIMAL(10, 2) NULL,
  remark VARCHAR(500) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS jxc_sales_order_detail (
  detail_id BIGINT NOT NULL AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  spu_id BIGINT NOT NULL,
  qty INT NOT NULL DEFAULT 0,
  booked_qty INT NULL,
  unfulfilled_qty INT NULL,
  unit_price DECIMAL(10, 2) NULL,
  discount_amount DECIMAL(10, 2) NULL,
  line_amount DECIMAL(10, 2) NULL,
  warehouse_id BIGINT NULL,
  remark VARCHAR(255) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (detail_id)
);

CREATE TABLE IF NOT EXISTS jxc_sales_return_order (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no VARCHAR(50) NOT NULL,
    doc_date DATETIME NOT NULL,
    customer_id BIGINT NOT NULL,
    origin_sales_id BIGINT,
    status INT DEFAULT 10,
    refund_amount DECIMAL(10,2),
    refund_method VARCHAR(50),
    remark VARCHAR(500),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS jxc_sales_return_detail (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku_id BIGINT,
    spu_id BIGINT,
    qty INT,
    unit_price DECIMAL(10,2),
    line_amount DECIMAL(10,2),
    warehouse_id BIGINT,
    remark VARCHAR(500),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS jxc_print_template (
  template_id BIGINT NOT NULL AUTO_INCREMENT,
  template_name VARCHAR(100) NOT NULL,
  biz_type VARCHAR(50) NOT NULL,
  paper_type VARCHAR(50) NULL,
  paper_width_mm INT NULL,
  paper_height_mm INT NULL,
  design_json CLOB NULL,
  is_default TINYINT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (template_id)
);

CREATE TABLE IF NOT EXISTS jxc_file_resource (
  file_id BIGINT NOT NULL AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(128) NULL,
  size BIGINT NULL,
  storage_path VARCHAR(512) NOT NULL,
  sha256 VARCHAR(64) NULL,
  create_time TIMESTAMP NULL,
  update_time TIMESTAMP NULL,
  create_by BIGINT NULL,
  update_by BIGINT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (file_id)
);

CREATE TABLE IF NOT EXISTS jxc_transfer_order (
  transfer_id BIGINT NOT NULL AUTO_INCREMENT,
  transfer_no VARCHAR(64) NOT NULL,
  from_warehouse_id BIGINT NULL,
  to_warehouse_id BIGINT NULL,
  from_warehouse_name VARCHAR(100) NULL,
  to_warehouse_name VARCHAR(100) NULL,
  status INT DEFAULT 0,
  transfer_date TIMESTAMP NULL,
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time TIMESTAMP NULL,
  updated_by BIGINT NULL,
  update_time TIMESTAMP NULL,
  deleted INT DEFAULT 0,
  PRIMARY KEY (transfer_id),
  UNIQUE (transfer_no)
);

CREATE TABLE IF NOT EXISTS jxc_transfer_order_detail (
  detail_id BIGINT NOT NULL AUTO_INCREMENT,
  transfer_id BIGINT NOT NULL,
  sku_id BIGINT NULL,
  sku_code VARCHAR(64) NULL,
  sku_name VARCHAR(200) NULL,
  attr1 VARCHAR(100) NULL,
  attr2 VARCHAR(100) NULL,
  qty INT NULL,
  cost_price DECIMAL(18,2) NULL,
  deleted INT DEFAULT 0,
  PRIMARY KEY (detail_id)
);

CREATE TABLE IF NOT EXISTS jxc_assembly_order (
  assembly_id BIGINT NOT NULL AUTO_INCREMENT,
  assembly_no VARCHAR(64) NOT NULL,
  warehouse_id BIGINT NULL,
  warehouse_name VARCHAR(100) NULL,
  type INT NULL,
  status INT DEFAULT 0,
  assembly_date TIMESTAMP NULL,
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time TIMESTAMP NULL,
  updated_by BIGINT NULL,
  update_time TIMESTAMP NULL,
  deleted INT DEFAULT 0,
  PRIMARY KEY (assembly_id),
  UNIQUE (assembly_no)
);

CREATE TABLE IF NOT EXISTS jxc_assembly_order_detail (
  detail_id BIGINT NOT NULL AUTO_INCREMENT,
  assembly_id BIGINT NOT NULL,
  sku_id BIGINT NULL,
  sku_code VARCHAR(64) NULL,
  sku_name VARCHAR(200) NULL,
  attr1 VARCHAR(100) NULL,
  attr2 VARCHAR(100) NULL,
  qty INT NULL,
  cost_price DECIMAL(18,2) NULL,
  item_type INT NULL,
  deleted INT DEFAULT 0,
  PRIMARY KEY (detail_id)
);
